spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/eason-goods?characterEncoding=utf-8&useSSL=false
    username: root
    password: GAKqD8q8s/fbxM9YUiiMpaj0hYp1LuPCda0DkR/B3v/fXpra1vKP+9cBtrXTwYJrDweDnAsFuscHiP5C3XZ6DA==
    decrypt: true
    public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIdafBFEbA+F7zB0RcwPOFzGUSo5tB2ggQh2Ay0MlKjlt9oKFfIHDKzt9jim+mZHONZsgOUktccAb0nFYX4TlikCAwEAAQ==
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  flyway:
    clean-disabled: false
    locations: classpath:db/migration,classpath:db/dev.migration
    out-of-order: true
    table: schema_goods_version

logging:
  file:
    path: /Users/colin/logs/eason/goods
    name: eason-goods
  level:
    com.eason.merchant: debug


