server:
  port: 9002

spring:
  application:
    name: eason-goods
  profiles:
    include: web, mysql
    active: local
  cache:
    ehcache:
      config: classpath:ehcache.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

cartisan:
  info:
    title: Eason Goods
    serviceUrl: http://www.cartisan.com
    version: 1.0
    contact:
      name: colin
      url: zhang_colin.github.com
      email: zhang_colin@163.com

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
